server:
  error:
    include-stacktrace: on_param

spring:

  datasource:
    url: jdbc:mysql://localhost:3306/code_challenge?createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: SequenciaDeCaracteresParaAssinarToken
  expiration: 86400000

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
      springframework:
        web: DEBUG
        filter:
          CommonsRequestLoggingFilter: DEBUG
          client:
            RestTemplate: DEBUG